# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 17:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketr', '0002_auto_20170218_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 2, 18, 17, 57, 51, 2570)),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2017, 2, 18, 17, 57, 51, 2592)),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 2, 18, 17, 57, 51, 2424)),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2017, 2, 18, 17, 57, 51, 2539)),
        ),
    ]
