# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 18:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketr', '0003_auto_20170218_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_price',
            field=models.FloatField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 2, 18, 18, 5, 4, 980742)),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2017, 2, 18, 18, 5, 4, 980761)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 2, 18, 18, 5, 4, 980695)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2017, 2, 18, 18, 5, 4, 980720)),
        ),
    ]
