# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketr', '0006_auto_20170218_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.CharField(max_length=128),
        ),
    ]
