# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticketr', '0013_auto_20170226_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventowner',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
