# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticketr', '0014_eventowner_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventowner',
            name='image',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
