# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticketr', '0016_auto_20170227_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ticket_price',
        ),
        migrations.AddField(
            model_name='event',
            name='privacy',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='resell',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='resell_amount',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='resell_when',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
    ]
