# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticketr', '0018_auto_20170302_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='quantity_sold',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
