# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketr', '0019_auto_20170307_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='quantity_sold',
            field=models.IntegerField(default=0),
        ),
    ]
