# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketr', '0020_auto_20170307_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
