# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketr', '0022_ticketqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketqueue',
            name='ticket_quantity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
