# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticketr', '0023_ticketqueue_ticket_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketqueue',
            name='time_inserted',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
