# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketr', '0024_ticketqueue_time_inserted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketqueue',
            name='time_inserted',
            field=models.TimeField(null=True),
        ),
    ]
