# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketr', '0026_auto_20170310_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('order_code', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='resell_amount',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='order',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketr.Event'),
        ),
        migrations.AddField(
            model_name='order',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketr.Ticket'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
