# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketr', '0027_auto_20170322_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'orders'},
        ),
    ]
