# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketr', '0031_auto_20170322_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='event_name',
            field=models.CharField(default='Hello World', max_length=128),
            preserve_default=False,
        ),
    ]
