# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketr', '0032_order_event_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='event_name',
        ),
    ]
