# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketr', '0033_remove_order_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
