# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketr', '0034_order_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(max_length=24),
        ),
    ]
