# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketr', '0036_order_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResellList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reason', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketr.Order')),
            ],
        ),
    ]
