# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 14:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketr', '0037_reselllist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reselllist',
            options={'verbose_name_plural': 'ResellLists'},
        ),
        migrations.AddField(
            model_name='reselllist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
