# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketr', '0041_remove_reselllist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='for_sale',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
