# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketr', '0043_auto_20170403_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='reselllist',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticketr.Event'),
            preserve_default=False,
        ),
    ]
