# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketr', '0044_reselllist_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reselllist',
            name='event',
        ),
    ]
