# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketr', '0048_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='background',
            field=models.FileField(default=1, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(upload_to=b''),
        ),
    ]
