# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketr', '0049_auto_20170421_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='background',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='order',
            name='qrcode',
            field=models.FileField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
