# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketr', '0051_auto_20170422_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='background',
            field=models.FileField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(upload_to=b''),
        ),
    ]
