# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketr', '0052_auto_20170422_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventowner',
            name='image',
            field=models.FileField(upload_to=b''),
        ),
    ]
