# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketr', '0053_auto_20170423_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketr.Event')),
            ],
            options={
                'verbose_name_plural': 'Invite Codes',
            },
        ),
    ]
